### ISSUE TITLE
Not working on mac OS X 10.6.8

### ISSUE THREAD

**Issue by Sajam** [develar/7zip-bin#1]
7za binary not working on my mac OS X 10.6.8

```
pc16:7zip-bin-mac daniel$ pwd
/Users/daniel/projects/XXX/node_modules/7zip-bin-mac
pc16:7zip-bin-mac daniel$ ./7za 
Illegal instruction
pc16:7zip-bin-mac daniel$ ./7za -v
Illegal instruction
```

Help would be much appreciated!

Thanks,
Daniel

**Comment by develar** [comment]
Your macos version is very outdated. Even stable default configuration on Travis uses `OS X 10.11`. Current user macOs version is `10.12`.
