### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mrawdon** [develar/7zip-bin#10]
Are you sure this can be licensed under MIT?  I would think you'd need to follow the 7z license here https://www.7-zip.org/license.txt

**Comment by develar** [comment]
> Redistributions in binary form must reproduce related license information from this file.

MIT license for the source code of this project. 

 > You can use 7-Zip on any computer, including a computer in a commercial
    organization. You don't need to register or pay for 7-Zip.

So, users of this package don't need to pay or do anything else.

**Comment by fritx** [comment]
Three 7zip eco developers here 👀

**Comment by jelhan** [comment]
This repository contains 7-Zip binaries as stated in the readme. Those binaries are not under MIT but under the following licenses:

- The "GNU LGPL"
- The "GNU LGPL" with "unRAR license restriction"
- The "BSD 3-clause License"
-  The "BSD 2-clause License" for some code

Those licenses require that license text is included when redistributing a binary. For example, the BSD-3-Clause contains the following obligation:

> 2. Redistributions in binary form must reproduce the above copyright notice,
>   this list of conditions and the following disclaimer in the documentation
>   and/or other materials provided with the distribution.

The current situation violates the license.

Please see https://github.com/ollm/7zip-bin-full/ as an example how it's done correctly without violating license terms.
