### ISSUE TITLE
Add windows arm64 binary

### ISSUE THREAD

**Issue by UppaJung** [develar/7zip-bin#18]
7zip-bin doesn't work in Parallels on M1 macs or any other Windows machine running on Arm64 architectures.  Please recompile for arm64.

Among other things, this breaks electron-builder.
https://github.com/electron-userland/electron-builder/issues/6677

**Comment by dennisameling** [comment]
See https://github.com/develar/7zip-bin/pull/13  where I added that binary 😊 Just waiting for someone to merge it

**Comment by dennisameling** [comment]
Now that #13 has been merged, the only thing that's left is to bump the version in `package.json` and do an `npm publish` on this package (https://www.npmjs.com/package/7zip-bin).

Then we can update `electron-userland/electron-builder` to reference the new version: https://github.com/electron-userland/electron-builder/search?q=7zip-bin

CC @develar

**Comment by develar** [comment]
Published 7zip-bin@5.2.0.
