### ISSUE TITLE
RISCV 7za bin

### ISSUE THREAD

**Issue by chLFF** [develar/7zip-bin#25]
`⨯ ENOENT: no such file or directory, chmod '/home/bianbu/my-electron-app/node_modules/7zip-bin/linux/riscv64/7za'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, chmod '/home/bianbu/my-electron-app/node_modules/7zip-bin/linux/riscv64/7za'`

Though i can fix this by building from source, still wish a RISCV 7za bin installed with 7zip-bin.

**Comment by mmaietta** [comment]
There's no provided binary for RISCV via https://www.7-zip.org/download.html so I'm going to close this as Not Planned
