### ISSUE TITLE
Different versions for linux, windows and mac

### ISSUE THREAD

**Issue by nknapp** [develar/7zip-bin#4]
I've been wondering, why the linux-version in this package is still 16.02 but the windows-version has updated to 18.0.1. 

I'm asking, because 16.02 does not support creating zip-files to stdout, which I would like to do.

**Comment by develar** [comment]
Because p7zip is not yet updated (https://sourceforge.net/projects/p7zip/).

**Comment by nknapp** [comment]
Ah, thanks
