### ISSUE TITLE
problems with 7zip mac - buggy rename

### ISSUE THREAD

**Issue by lukeapage** [develar/7zip-bin#7]
Hi,

When certain repos are compressed with certain options, the rename command doesn't work.. only on mac.

We were looking around for where 7zip on mac came from to see if it can be updated, but we can't find any project to make a mac build - was this compiled yourself?

**Comment by develar** [comment]
https://sourceforge.net/projects/p7zip/

Version for mac and Linux is quite outdated (2016), and p7zip author doesn't have plans to update it, as far I know.
